### ISSUE TITLE
Aim of the library (list of features we want)

### ISSUE THREAD

**Issue by tgalopin** [tgalopin/FOSMessage#1]
Hello,

This library has a few core ideas:

- Independant from a framework (and from a persistance layer such as Doctrine, Propel, etc.)
- System of inbox / sent box
- Threaded conversations
- Multiple participants per conversation
I think for the moment we don't need the SPAM detection and the archive system. We could add these systems after the basics.

However, beyond these core concepts we need to define more precisely which feature we want to implement. The best way I can think of to do so is by writing scenarii. Here is mine:

- A user has an inbox that consists of a list of threads, displaying the title of the thread, the creator and the creation date of the thread, the date and the sender of last message, a link to go on the last message and a checkbox to apply operations on multiple thread ;
- A user has a send box that have the same display as the inbox but the creator of the thread is not displayed ;
- A user can click on a link to send a new message: he has a recipient field with auto-completion, a title field and a message field. When he send a message, a thread is created and the user is redirected to it ;
- A user can view a thread: it's a list of messages with their authors, content and date. When this user view the thread, it's marked as "read" for this participant
- A user can delete one or multiple threads using checkboxes on the lists
- A user can mark one or multiple threads as "read" / "unread" using checkboxes on the lists

(this list is not finished, please contribute !)

Don't hesitate to propose your ideas in the comments. If you use the current bundle, please also explain what you use and how you implemented things.

**Comment by ojhaujjwal** [comment]
+1
